homepage:
    pattern:  /
    defaults: { _controller: Cursosf2StaticBundle:Default:homepage }

contenido_estatico:
    pattern: /sitio/{pagina}
    defaults: { _controller: Cursosf2StaticBundle:Default:sitio }
_contenido_estatico:
    pattern: /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: contenido_estatico }
