Cursosf2GeolocalizacionBundle:
    resource: "@Cursosf2GeolocalizacionBundle/Controller/"
    type:     annotation
    prefix:   /

Cursosf2XchangeRatesBundle:
    resource: "@Cursosf2XchangeRatesBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
