Cursosf2ReunionesBundle:
    resource: "@Cursosf2ReunionesBundle/Resources/config/routing.yml"
    prefix:   /

Cursosf2StaticBundle:
    resource: "@Cursosf2StaticBundle/Resources/config/routing.yml"
    prefix:   /

Cursosf2UsuariosBundle:
    resource: "@Cursosf2UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

Cursosf2GrupoBundle:
    resource: "@Cursosf2GrupoBundle/Resources/config/routing.yml"
    prefix:   /

Cursosf2GeolocalizacionBundle:
    resource: "@Cursosf2GeolocalizacionBundle/Controller/"
    type:     annotation
    prefix:   /

Cursosf2XchangeRatesBundle:
    resource: "@Cursosf2XchangeRatesBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
