<?php

namespace Cursosf2\ReunionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipanteRepository extends EntityRepository
{
}