<?php

namespace Cursosf2\ReunionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends EntityRepository
{
    /**
     * Devuelve las reuniones cuya fecha de reunión sea superior a una fecha dada
     * @param DateTime|null $fecha
     * @param int $limit
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function findProximasReuniones(\DateTime $fecha = null, $limit = 5) {
        if (!$fecha) {
            $fecha = new \DateTime('now');
        }
        $em = $this->getEntityManager();
        $dql = 'SELECT r FROM Cursosf2ReunionesBundle:Reunion r
                  WHERE r.fecha_reunion > :fecha
                  ORDER BY r.fecha_reunion ASC';
        return $em->createQuery($dql)->
            setParameter('fecha', $fecha)->
            setMaxResults($limit)->
            execute();
    }
}