<?php

namespace Cursosf2\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function findTodosLosGrupos($usuario)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                    SELECT g,m,u FROM Cursosf2GrupoBundle:Grupo g
                    JOIN g.miembros m JOIN m.usuario u
                    WHERE m.usuario = :id'
                )->setParameter('id', $usuario);
        return $query->execute();
    }
}