parameters:
#    cursosf2_grupo.example.class: Cursosf2\GrupoBundle\Example

services:
#    cursosf2_grupo.example:
#        class: %cursosf2_grupo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
