<?php

namespace Cursosf2\GeolocalizacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeolocalizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeolocalizacionRepository extends EntityRepository
{
}
