<?php

namespace Cursosf2\GrupoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends EntityRepository
{
}